# Generated by Django 5.2 on 2025-04-15 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numeroTelephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numeroTelephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20)),
                ('salaire', models.FloatField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numeroTelephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('adresse', models.TextField()),
                ('cin', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numeroTelephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=20)),
                ('salaire', models.FloatField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixFacture', models.FloatField()),
                ('dateFacture', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPatient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreRendezVous', models.CharField(max_length=255)),
                ('typeRendezVous', models.CharField(max_length=100)),
                ('dateRendezVous', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPatient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetDemande', models.CharField(max_length=255)),
                ('bodyDemande', models.TextField()),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionPatient.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPatient.patient')),
                ('secretaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionPatient.secretaire')),
            ],
        ),
    ]
