# Generated by Django 5.2 on 2025-04-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='cin',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='email',
            field=models.EmailField(max_length=191),
        ),
        migrations.AlterField(
            model_name='demande',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='gestionPatient.medecin'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='gestionPatient.patient'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='secretaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='gestionPatient.secretaire'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='gestionPatient.patient'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='email',
            field=models.EmailField(max_length=191),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='gestionPatient.patient'),
        ),
        migrations.AlterField(
            model_name='secretaire',
            name='cin',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='secretaire',
            name='email',
            field=models.EmailField(max_length=191),
        ),
    ]
