# Generated by Django 5.2 on 2025-04-28 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0003_administrateur_date_joined_administrateur_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='medecin',
            name='adresse',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medecin',
            name='descriptionMedecin',
            field=models.TextField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medecin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='descriptionRendezVous',
            field=models.TextField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to='gestionPatient.medecin'),
        ),
        migrations.AddField(
            model_name='secretaire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
