# Generated by Django 5.2 on 2025-04-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0004_administrateur_image_medecin_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(default='En Cours', max_length=30),
        ),
    ]
