# Generated by Django 5.2 on 2025-05-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0005_rendezvous_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreRendezVous', models.CharField(max_length=255)),
                ('typeRendezVous', models.CharField(max_length=100)),
                ('dateRendezVous', models.DateField()),
                ('descriptionRendezVous', models.TextField(default=True, max_length=100)),
                ('statut', models.CharField(default='False', max_length=30)),
                ('medecin', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecin_archive', to='gestionPatient.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_archive', to='gestionPatient.patient')),
            ],
        ),
    ]
