# Generated by Django 5.2 on 2025-05-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0006_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages_secretaire_medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=250)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_secretaire', to='gestionPatient.medecin')),
                ('secretaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretaire_medecin', to='gestionPatient.secretaire')),
            ],
        ),
    ]
