# Generated by Django 5.2 on 2025-05-04 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0007_messages_secretaire_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 12, 25, 6, 622889, tzinfo=datetime.timezone.utc)),
        ),
    ]
