# Generated by Django 5.2 on 2025-05-04 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0008_messages_secretaire_medecin_date_denvoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_secretaire_medecin',
            name='vu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 16, 54, 29, 105502, tzinfo=datetime.timezone.utc)),
        ),
    ]
