# Generated by Django 5.2 on 2025-05-04 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0010_messages_secretaire_medecin_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='prix_consultation',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 21, 2, 28, 656800, tzinfo=datetime.timezone.utc)),
        ),
    ]
