# Generated by Django 5.2 on 2025-05-05 16:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0011_medecin_prix_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateField(default=datetime.datetime(2025, 5, 5, 16, 49, 14, 846165, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='RapportMedicalPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('date_rapport', models.DateTimeField(default=datetime.datetime(2025, 5, 5, 16, 49, 14, 846897, tzinfo=datetime.timezone.utc))),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapport_patient_medecin', to='gestionPatient.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapport_patient', to='gestionPatient.patient')),
            ],
        ),
    ]
