# Generated by Django 5.2 on 2025-05-05 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0012_alter_messages_secretaire_medecin_date_denvoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 17, 50, 29, 953369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rapportmedicalpatient',
            name='date_rapport',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 17, 50, 29, 954351, tzinfo=datetime.timezone.utc)),
        ),
    ]
