# Generated by Django 5.2 on 2025-05-05 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0014_facture_note_supplemtaire_alter_facture_datefacture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='note_supplemtaire',
            new_name='note_supplementaire',
        ),
        migrations.AlterField(
            model_name='facture',
            name='dateFacture',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 20, 26, 19, 448822, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 20, 26, 19, 451264, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rapportmedicalpatient',
            name='date_rapport',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 20, 26, 19, 451749, tzinfo=datetime.timezone.utc)),
        ),
    ]
