# Generated by Django 5.2 on 2025-05-06 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0015_rename_note_supplemtaire_facture_note_supplementaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 11, 16, 52, 925622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rapportmedicalpatient',
            name='date_rapport',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 11, 16, 52, 927109, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
