# Generated by Django 5.2 on 2025-05-06 11:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0016_alter_messages_secretaire_medecin_date_denvoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 11, 17, 51, 447896, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rapportmedicalpatient',
            name='date_rapport',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 11, 17, 51, 448470, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixFacture', models.FloatField()),
                ('dateFacture', models.DateTimeField(default=datetime.datetime(2025, 5, 6, 11, 17, 51, 445664, tzinfo=datetime.timezone.utc))),
                ('note_supplementaire', models.TextField(default=False, max_length=150)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='gestionPatient.patient')),
            ],
        ),
    ]
