# Generated by Django 5.2 on 2025-05-06 11:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0017_alter_messages_secretaire_medecin_date_denvoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='rendezvous',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_rendezvous', to='gestionPatient.rendezvous'),
        ),
        migrations.AddField(
            model_name='rapportmedicalpatient',
            name='rendezvous',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_rendezvous', to='gestionPatient.rendezvous'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='dateFacture',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 11, 20, 56, 119019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 11, 20, 56, 121664, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rapportmedicalpatient',
            name='date_rapport',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 11, 20, 56, 122410, tzinfo=datetime.timezone.utc)),
        ),
    ]
