# Generated by Django 5.2 on 2025-05-08 20:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0019_alter_administrateur_image_alter_facture_datefacture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='dateFacture',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 20, 39, 50, 68874, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 20, 39, 50, 75180, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rapportmedicalpatient',
            name='date_rapport',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 20, 39, 50, 78116, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Messages_admin_medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default=False, max_length=30)),
                ('destination', models.CharField(default=False, max_length=30)),
                ('message', models.TextField(max_length=250)),
                ('date_denvoi', models.DateTimeField(default=datetime.datetime(2025, 5, 8, 20, 39, 50, 80318, tzinfo=datetime.timezone.utc))),
                ('vu', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_medecin', to='gestionPatient.administrateur')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_admin', to='gestionPatient.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Messages_admin_secretaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default=False, max_length=30)),
                ('destination', models.CharField(default=False, max_length=30)),
                ('message', models.TextField(max_length=250)),
                ('date_denvoi', models.DateTimeField(default=datetime.datetime(2025, 5, 8, 20, 39, 50, 82477, tzinfo=datetime.timezone.utc))),
                ('vu', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_secretaire', to='gestionPatient.administrateur')),
                ('secretaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretaire_admin', to='gestionPatient.secretaire')),
            ],
        ),
    ]
