# Generated by Django 5.2 on 2025-05-10 13:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPatient', '0020_alter_facture_datefacture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='secretaire',
        ),
        migrations.AddField(
            model_name='demande',
            name='rendezvous',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='demande_rendezvous', to='gestionPatient.rendezvous'),
        ),
        migrations.AddField(
            model_name='demande',
            name='statut',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='demande',
            name='objetDemande',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='facture',
            name='dateFacture',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 13, 1, 41, 101572, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messages_admin_medecin',
            name='date_denvoi',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 13, 1, 41, 114286, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messages_admin_secretaire',
            name='date_denvoi',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 13, 1, 41, 115847, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messages_secretaire_medecin',
            name='date_denvoi',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 13, 1, 41, 108482, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rapportmedicalpatient',
            name='date_rapport',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 13, 1, 41, 110286, tzinfo=datetime.timezone.utc)),
        ),
    ]
